package com.site.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDealer<M extends BaseDealer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}

	public java.lang.Long getAreaId() {
		return getLong("area_id");
	}

	public void setRegionId(java.lang.Long regionId) {
		set("region_id", regionId);
	}

	public java.lang.Long getRegionId() {
		return getLong("region_id");
	}

	public void setAreaManagerUserId(java.lang.Long areaManagerUserId) {
		set("area_manager_user_id", areaManagerUserId);
	}

	public java.lang.Long getAreaManagerUserId() {
		return getLong("area_manager_user_id");
	}

	public void setBusinessManagerUserId(java.lang.Long businessManagerUserId) {
		set("business_manager_user_id", businessManagerUserId);
	}

	public java.lang.Long getBusinessManagerUserId() {
		return getLong("business_manager_user_id");
	}

	public void setUpstreamName(java.lang.String upstreamName) {
		set("upstream_name", upstreamName);
	}

	public java.lang.String getUpstreamName() {
		return getStr("upstream_name");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setLevel(java.lang.String level) {
		set("level", level);
	}

	public java.lang.String getLevel() {
		return getStr("level");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}

	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserId(java.lang.Long updateUserId) {
		set("update_user_id", updateUserId);
	}

	public java.lang.Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	public void setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.String getIsDelete() {
		return getStr("is_delete");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}

	public java.lang.String getVersion() {
		return getStr("version");
	}

	public void setOrderCalculateCode(java.lang.String orderCalculateCode) {
		set("order_calculate_code", orderCalculateCode);
	}

	public java.lang.String getOrderCalculateCode() {
		return getStr("order_calculate_code");
	}

	public void setOldLevel(java.lang.String oldLevel) {
		set("old_level", oldLevel);
	}

	public java.lang.String getOldLevel() {
		return getStr("old_level");
	}

	public void setChangeLevelTime(java.util.Date changeLevelTime) {
		set("change_level_time", changeLevelTime);
	}

	public java.util.Date getChangeLevelTime() {
		return get("change_level_time");
	}

}
