package com.site.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDealerInventoryDataVersion<M extends BaseDealerInventoryDataVersion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}

	public java.lang.Long getAreaId() {
		return getLong("area_id");
	}

	public void setAreaName(java.lang.String areaName) {
		set("area_name", areaName);
	}

	public java.lang.String getAreaName() {
		return getStr("area_name");
	}

	public void setRegionId(java.lang.Long regionId) {
		set("region_id", regionId);
	}

	public java.lang.Long getRegionId() {
		return getLong("region_id");
	}

	public void setRegionName(java.lang.String regionName) {
		set("region_name", regionName);
	}

	public java.lang.String getRegionName() {
		return getStr("region_name");
	}

	public void setAreaManagerUserId(java.lang.Long areaManagerUserId) {
		set("area_manager_user_id", areaManagerUserId);
	}

	public java.lang.Long getAreaManagerUserId() {
		return getLong("area_manager_user_id");
	}

	public void setAreaManagerUserName(java.lang.String areaManagerUserName) {
		set("area_manager_user_name", areaManagerUserName);
	}

	public java.lang.String getAreaManagerUserName() {
		return getStr("area_manager_user_name");
	}

	public void setAreaManagerEmployeeNumber(java.lang.String areaManagerEmployeeNumber) {
		set("area_manager_employee_number", areaManagerEmployeeNumber);
	}

	public java.lang.String getAreaManagerEmployeeNumber() {
		return getStr("area_manager_employee_number");
	}

	public void setBusinessManagerUserId(java.lang.Long businessManagerUserId) {
		set("business_manager_user_id", businessManagerUserId);
	}

	public java.lang.Long getBusinessManagerUserId() {
		return getLong("business_manager_user_id");
	}

	public void setBusinessManagerUserName(java.lang.String businessManagerUserName) {
		set("business_manager_user_name", businessManagerUserName);
	}

	public java.lang.String getBusinessManagerUserName() {
		return getStr("business_manager_user_name");
	}

	public void setBusinessManagerEmployeeNumber(java.lang.String businessManagerEmployeeNumber) {
		set("business_manager_employee_number", businessManagerEmployeeNumber);
	}

	public java.lang.String getBusinessManagerEmployeeNumber() {
		return getStr("business_manager_employee_number");
	}

	public void setDealerId(java.lang.Long dealerId) {
		set("dealer_id", dealerId);
	}

	public java.lang.Long getDealerId() {
		return getLong("dealer_id");
	}

	public void setDealerName(java.lang.String dealerName) {
		set("dealer_name", dealerName);
	}

	public java.lang.String getDealerName() {
		return getStr("dealer_name");
	}

	public void setDealerLevel(java.lang.String dealerLevel) {
		set("dealer_level", dealerLevel);
	}

	public java.lang.String getDealerLevel() {
		return getStr("dealer_level");
	}

	public void setDealerCode(java.lang.String dealerCode) {
		set("dealer_code", dealerCode);
	}

	public java.lang.String getDealerCode() {
		return getStr("dealer_code");
	}

	public void setMonth(java.lang.Integer month) {
		set("month", month);
	}

	public java.lang.Integer getMonth() {
		return getInt("month");
	}

	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}

	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}

	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public void setUpstreamName(java.lang.String upstreamName) {
		set("upstream_name", upstreamName);
	}

	public java.lang.String getUpstreamName() {
		return getStr("upstream_name");
	}

	public void setPrecedingMonthActualStockQuantity(java.lang.Long precedingMonthActualStockQuantity) {
		set("preceding_month_actual_stock_quantity", precedingMonthActualStockQuantity);
	}

	public java.lang.Long getPrecedingMonthActualStockQuantity() {
		return getLong("preceding_month_actual_stock_quantity");
	}

	public void setLastMonthPlanPurchaseQuantity(java.lang.Long lastMonthPlanPurchaseQuantity) {
		set("last_month_plan_purchase_quantity", lastMonthPlanPurchaseQuantity);
	}

	public java.lang.Long getLastMonthPlanPurchaseQuantity() {
		return getLong("last_month_plan_purchase_quantity");
	}

	public void setLastMonthActualPurchaseQuantity(java.lang.Long lastMonthActualPurchaseQuantity) {
		set("last_month_actual_purchase_quantity", lastMonthActualPurchaseQuantity);
	}

	public java.lang.Long getLastMonthActualPurchaseQuantity() {
		return getLong("last_month_actual_purchase_quantity");
	}

	public void setLastMonthPlanSalesQuantity(java.lang.Long lastMonthPlanSalesQuantity) {
		set("last_month_plan_sales_quantity", lastMonthPlanSalesQuantity);
	}

	public java.lang.Long getLastMonthPlanSalesQuantity() {
		return getLong("last_month_plan_sales_quantity");
	}

	public void setLastMonthActualSalesQuantity(java.lang.Long lastMonthActualSalesQuantity) {
		set("last_month_actual_sales_quantity", lastMonthActualSalesQuantity);
	}

	public java.lang.Long getLastMonthActualSalesQuantity() {
		return getLong("last_month_actual_sales_quantity");
	}

	public void setLastMonthActualSalesQuantityHeadOffice(java.lang.Long lastMonthActualSalesQuantityHeadOffice) {
		set("last_month_actual_sales_quantity_head_office", lastMonthActualSalesQuantityHeadOffice);
	}

	public java.lang.Long getLastMonthActualSalesQuantityHeadOffice() {
		return getLong("last_month_actual_sales_quantity_head_office");
	}

	public void setLastMonthTheoryStockQuantity(java.lang.Long lastMonthTheoryStockQuantity) {
		set("last_month_theory_stock_quantity", lastMonthTheoryStockQuantity);
	}

	public java.lang.Long getLastMonthTheoryStockQuantity() {
		return getLong("last_month_theory_stock_quantity");
	}

	public void setLastMonthActualStockQuantity(java.lang.Long lastMonthActualStockQuantity) {
		set("last_month_actual_stock_quantity", lastMonthActualStockQuantity);
	}

	public java.lang.Long getLastMonthActualStockQuantity() {
		return getLong("last_month_actual_stock_quantity");
	}

	public void setLastMonthPurchaseQuantity(java.math.BigDecimal lastMonthPurchaseQuantity) {
		set("last_month_purchase_quantity", lastMonthPurchaseQuantity);
	}

	public java.math.BigDecimal getLastMonthPurchaseQuantity() {
		return get("last_month_purchase_quantity");
	}

	public void setLastMonthInventoryDay(java.math.BigDecimal lastMonthInventoryDay) {
		set("last_month_inventory_day", lastMonthInventoryDay);
	}

	public java.math.BigDecimal getLastMonthInventoryDay() {
		return get("last_month_inventory_day");
	}

	public void setPlanPurchaseQuantity(java.lang.Long planPurchaseQuantity) {
		set("plan_purchase_quantity", planPurchaseQuantity);
	}

	public java.lang.Long getPlanPurchaseQuantity() {
		return getLong("plan_purchase_quantity");
	}

	public void setActualPurchaseQuantity(java.lang.Long actualPurchaseQuantity) {
		set("actual_purchase_quantity", actualPurchaseQuantity);
	}

	public java.lang.Long getActualPurchaseQuantity() {
		return getLong("actual_purchase_quantity");
	}

	public void setPlanSalesQuantity(java.lang.Long planSalesQuantity) {
		set("plan_sales_quantity", planSalesQuantity);
	}

	public java.lang.Long getPlanSalesQuantity() {
		return getLong("plan_sales_quantity");
	}

	public void setActualSalesQuantity(java.lang.Long actualSalesQuantity) {
		set("actual_sales_quantity", actualSalesQuantity);
	}

	public java.lang.Long getActualSalesQuantity() {
		return getLong("actual_sales_quantity");
	}

	public void setTheoryStockQuantity(java.lang.Long theoryStockQuantity) {
		set("theory_stock_quantity", theoryStockQuantity);
	}

	public java.lang.Long getTheoryStockQuantity() {
		return getLong("theory_stock_quantity");
	}

	public void setActualStockQuantity(java.lang.Long actualStockQuantity) {
		set("actual_stock_quantity", actualStockQuantity);
	}

	public java.lang.Long getActualStockQuantity() {
		return getLong("actual_stock_quantity");
	}

	public void setPurchaseQuantity(java.math.BigDecimal purchaseQuantity) {
		set("purchase_quantity", purchaseQuantity);
	}

	public java.math.BigDecimal getPurchaseQuantity() {
		return get("purchase_quantity");
	}

	public void setInventoryDay(java.math.BigDecimal inventoryDay) {
		set("inventory_day", inventoryDay);
	}

	public java.math.BigDecimal getInventoryDay() {
		return get("inventory_day");
	}

	public void setDiffCause(java.lang.String diffCause) {
		set("diff_cause", diffCause);
	}

	public java.lang.String getDiffCause() {
		return getStr("diff_cause");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}

	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
	}

	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setCreateUserEmployeeNumber(java.lang.String createUserEmployeeNumber) {
		set("create_user_employee_number", createUserEmployeeNumber);
	}

	public java.lang.String getCreateUserEmployeeNumber() {
		return getStr("create_user_employee_number");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserId(java.lang.Long updateUserId) {
		set("update_user_id", updateUserId);
	}

	public java.lang.Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	public void setUpdateUserName(java.lang.String updateUserName) {
		set("update_user_name", updateUserName);
	}

	public java.lang.String getUpdateUserName() {
		return getStr("update_user_name");
	}

	public void setUpdateUserEmployeeNumber(java.lang.String updateUserEmployeeNumber) {
		set("update_user_employee_number", updateUserEmployeeNumber);
	}

	public java.lang.String getUpdateUserEmployeeNumber() {
		return getStr("update_user_employee_number");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return getStr("comment");
	}

	public void setArchiveTime(java.util.Date archiveTime) {
		set("archive_time", archiveTime);
	}

	public java.util.Date getArchiveTime() {
		return get("archive_time");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}

	public java.lang.String getVersion() {
		return getStr("version");
	}

	public void setOrderNum(java.lang.Long orderNum) {
		set("order_num", orderNum);
	}

	public java.lang.Long getOrderNum() {
		return getLong("order_num");
	}

	public void setDiffOrderNum(java.lang.Long diffOrderNum) {
		set("diff_order_num", diffOrderNum);
	}

	public java.lang.Long getDiffOrderNum() {
		return getLong("diff_order_num");
	}

	public void setPreSixMonthAverageSales(java.lang.Long preSixMonthAverageSales) {
		set("pre_six_month_average_sales", preSixMonthAverageSales);
	}

	public java.lang.Long getPreSixMonthAverageSales() {
		return getLong("pre_six_month_average_sales");
	}

}
