package com.site.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSecondaryDealerInventoryData<M extends BaseSecondaryDealerInventoryData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}

	public java.lang.Long getAreaId() {
		return getLong("area_id");
	}

	public void setRegionId(java.lang.Long regionId) {
		set("region_id", regionId);
	}

	public java.lang.Long getRegionId() {
		return getLong("region_id");
	}

	public void setAreaManagerUserId(java.lang.Long areaManagerUserId) {
		set("area_manager_user_id", areaManagerUserId);
	}

	public java.lang.Long getAreaManagerUserId() {
		return getLong("area_manager_user_id");
	}

	public void setBusinessManagerUserId(java.lang.Long businessManagerUserId) {
		set("business_manager_user_id", businessManagerUserId);
	}

	public java.lang.Long getBusinessManagerUserId() {
		return getLong("business_manager_user_id");
	}

	public void setDealerId(java.lang.Long dealerId) {
		set("dealer_id", dealerId);
	}

	public java.lang.Long getDealerId() {
		return getLong("dealer_id");
	}

	public void setMonth(java.lang.Integer month) {
		set("month", month);
	}

	public java.lang.Integer getMonth() {
		return getInt("month");
	}

	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}

	public java.lang.Long getProductId() {
		return getLong("product_id");
	}

	public void setPlanPurchaseQuantity(java.lang.Long planPurchaseQuantity) {
		set("plan_purchase_quantity", planPurchaseQuantity);
	}

	public java.lang.Long getPlanPurchaseQuantity() {
		return getLong("plan_purchase_quantity");
	}

	public void setActualPurchaseQuantity(java.lang.Long actualPurchaseQuantity) {
		set("actual_purchase_quantity", actualPurchaseQuantity);
	}

	public java.lang.Long getActualPurchaseQuantity() {
		return getLong("actual_purchase_quantity");
	}

	public void setPlanSalesQuantity(java.lang.Long planSalesQuantity) {
		set("plan_sales_quantity", planSalesQuantity);
	}

	public java.lang.Long getPlanSalesQuantity() {
		return getLong("plan_sales_quantity");
	}

	public void setActualSalesQuantity(java.lang.Long actualSalesQuantity) {
		set("actual_sales_quantity", actualSalesQuantity);
	}

	public java.lang.Long getActualSalesQuantity() {
		return getLong("actual_sales_quantity");
	}

	public void setActualSalesQuantityHeadOffice(java.lang.Long actualSalesQuantityHeadOffice) {
		set("actual_sales_quantity_head_office", actualSalesQuantityHeadOffice);
	}

	public java.lang.Long getActualSalesQuantityHeadOffice() {
		return getLong("actual_sales_quantity_head_office");
	}

	public void setTheoryStockQuantity(java.lang.Long theoryStockQuantity) {
		set("theory_stock_quantity", theoryStockQuantity);
	}

	public java.lang.Long getTheoryStockQuantity() {
		return getLong("theory_stock_quantity");
	}

	public void setActualStockQuantity(java.lang.Long actualStockQuantity) {
		set("actual_stock_quantity", actualStockQuantity);
	}

	public java.lang.Long getActualStockQuantity() {
		return getLong("actual_stock_quantity");
	}

	public void setInventoryDay(java.math.BigDecimal inventoryDay) {
		set("inventory_day", inventoryDay);
	}

	public java.math.BigDecimal getInventoryDay() {
		return get("inventory_day");
	}

	public void setDiffCause(java.lang.String diffCause) {
		set("diff_cause", diffCause);
	}

	public java.lang.String getDiffCause() {
		return getStr("diff_cause");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserId(java.lang.Long createUserId) {
		set("create_user_id", createUserId);
	}

	public java.lang.Long getCreateUserId() {
		return getLong("create_user_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserId(java.lang.Long updateUserId) {
		set("update_user_id", updateUserId);
	}

	public java.lang.Long getUpdateUserId() {
		return getLong("update_user_id");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return getStr("comment");
	}

	public void setOriginalTheoryStockQuantity(java.lang.Long originalTheoryStockQuantity) {
		set("original_theory_stock_quantity", originalTheoryStockQuantity);
	}

	public java.lang.Long getOriginalTheoryStockQuantity() {
		return getLong("original_theory_stock_quantity");
	}

	public void setRefStockQuantity(java.lang.Long refStockQuantity) {
		set("ref_stock_quantity", refStockQuantity);
	}

	public java.lang.Long getRefStockQuantity() {
		return getLong("ref_stock_quantity");
	}

	public void setRefInventoryDay(java.math.BigDecimal refInventoryDay) {
		set("ref_inventory_day", refInventoryDay);
	}

	public java.math.BigDecimal getRefInventoryDay() {
		return get("ref_inventory_day");
	}

	public void setLevelChangeFlag(java.lang.String levelChangeFlag) {
		set("level_change_flag", levelChangeFlag);
	}

	public java.lang.String getLevelChangeFlag() {
		return getStr("level_change_flag");
	}

	public void setLevelChangeId(java.lang.Long levelChangeId) {
		set("level_change_id", levelChangeId);
	}

	public java.lang.Long getLevelChangeId() {
		return getLong("level_change_id");
	}

	public void setPurchaseQuantity(java.math.BigDecimal purchaseQuantity) {
		set("purchase_quantity", purchaseQuantity);
	}

	public java.math.BigDecimal getPurchaseQuantity() {
		return get("purchase_quantity");
	}

	public void setOrderNum(java.lang.Long orderNum) {
		set("order_num", orderNum);
	}

	public java.lang.Long getOrderNum() {
		return getLong("order_num");
	}

	public void setDiffOrderNum(java.lang.Long diffOrderNum) {
		set("diff_order_num", diffOrderNum);
	}

	public java.lang.Long getDiffOrderNum() {
		return getLong("diff_order_num");
	}

	public void setPreSixMonthAverageSales(java.lang.Long preSixMonthAverageSales) {
		set("pre_six_month_average_sales", preSixMonthAverageSales);
	}

	public java.lang.Long getPreSixMonthAverageSales() {
		return getLong("pre_six_month_average_sales");
	}

}
