package com.site.core.model;

import com.site.core.model.base.BaseDealer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dealer extends BaseDealer<Dealer> {
	public static final Dealer dao = new Dealer().dao();
}
