package com.site.core.model;

import com.site.core.model.base.BaseDealerInventoryDataVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DealerInventoryDataVersion extends BaseDealerInventoryDataVersion<DealerInventoryDataVersion> {
	public static final DealerInventoryDataVersion dao = new DealerInventoryDataVersion().dao();
}
