package com.site.core.model;

import com.site.core.model.base.BaseDealerInventoryDataHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DealerInventoryDataHistory extends BaseDealerInventoryDataHistory<DealerInventoryDataHistory> {
	public static final DealerInventoryDataHistory dao = new DealerInventoryDataHistory().dao();
}
