package com.site.core.model;

import com.site.core.model.base.BaseDealerInventoryDataVersionList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DealerInventoryDataVersionList extends BaseDealerInventoryDataVersionList<DealerInventoryDataVersionList> {
	public static final DealerInventoryDataVersionList dao = new DealerInventoryDataVersionList().dao();
}
