package com.site.core.model;

import com.site.core.model.base.BaseDealerProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DealerProduct extends BaseDealerProduct<DealerProduct> {
	public static final DealerProduct dao = new DealerProduct().dao();
}
