package com.site.core.model;

import com.site.core.model.base.BaseOpenTimeManage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpenTimeManage extends BaseOpenTimeManage<OpenTimeManage> {
    public static final OpenTimeManage dao = new OpenTimeManage().dao();
}
