package com.site.core.model;

import com.site.core.model.base.BasePurchaseTotalProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseTotalProduct extends BasePurchaseTotalProduct<PurchaseTotalProduct> {
	public static final PurchaseTotalProduct dao = new PurchaseTotalProduct().dao();
}
