package com.site.core.model;

import com.site.core.model.base.BaseSecondaryDealerInventoryData;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecondaryDealerInventoryData extends BaseSecondaryDealerInventoryData<SecondaryDealerInventoryData> {
    public static final SecondaryDealerInventoryData dao = new SecondaryDealerInventoryData().dao();

    public static SecondaryDealerInventoryData init(Dealer dealer, User user) {
        SecondaryDealerInventoryData inventoryData = new SecondaryDealerInventoryData();
        inventoryData.setDealerId(dealer.getId());
        inventoryData.setAreaId(dealer.getAreaId());
        inventoryData.setAreaManagerUserId(dealer.getAreaManagerUserId());
        inventoryData.setRegionId(dealer.getRegionId());
        inventoryData.setBusinessManagerUserId(dealer.getBusinessManagerUserId());
        inventoryData.setCreateTime(new Date());
        inventoryData.setCreateUserId(user.getId());
        inventoryData.setUpdateUserId(user.getId());
        inventoryData.setUpdateTime(new Date());
        return inventoryData;
    }

    public BigDecimal getCustomActualSalesQuantity() {
        BigDecimal actualSalesQuantity = null;
        if (this.getActualSalesQuantityHeadOffice() != null) {
            actualSalesQuantity = new BigDecimal(this.getActualSalesQuantityHeadOffice());
        } else {
            if (this.getActualSalesQuantity() != null) {
                actualSalesQuantity = new BigDecimal(this.getActualSalesQuantity());
            }
        }
        return actualSalesQuantity;
    }
}
