package com.site.core.model;

import com.site.core.model.base.BaseSendEmailList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SendEmailList extends BaseSendEmailList<SendEmailList> {
	public static final SendEmailList dao = new SendEmailList().dao();
}
